# Generated by Django 5.2.5 on 2025-08-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.BooleanField(default=True)),
                ('session', models.CharField(max_length=255, unique=True)),
                ('chat_user', models.TextField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('chat_input', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('exam_labs', models.TextField(blank=True, null=True)),
                ('treatment_recommendations', models.TextField(blank=True, null=True)),
                ('chatbot_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_project_app.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_found', models.BooleanField(default=False)),
                ('outside_range', models.BooleanField(default=False)),
                ('named_entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='llm_project_app.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('questionTimestamp', models.DateTimeField(auto_now_add=True)),
                ('answerTimestamp', models.DateTimeField(auto_now=True)),
                ('chatbot_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='llm_project_app.chatbot')),
            ],
        ),
    ]
