# Generated by Django 5.2.5 on 2025-08-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
