# Generated by Django 5.2.5 on 2025-08-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0002_chatbot_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chain_of_thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='chain_of_thought',
            field=models.TextField(blank=True, null=True),
        ),
    ]
