# Generated by Django 5.2.5 on 2025-08-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0003_chatbot_chain_of_thought_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner_llm_role', models.CharField(blank=True, max_length=255, null=True)),
                ('ner_llm_content', models.TextField(blank=True, null=True)),
                ('ner_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ner_model_temperature', models.FloatField(blank=True, null=True)),
                ('follow_up_context', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_model', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_model_temperature', models.FloatField(blank=True, null=True)),
                ('follow_up_max_tokens', models.IntegerField(blank=True, null=True)),
                ('summarise_system_content', models.TextField(blank=True, null=True)),
                ('summarise_user_content', models.TextField(blank=True, null=True)),
                ('summarise_model', models.CharField(blank=True, max_length=255, null=True)),
                ('summarise_model_temperature', models.FloatField(blank=True, null=True)),
                ('prediction_message', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction_max_tokens', models.IntegerField(blank=True, null=True)),
                ('prediction_model_temperature', models.FloatField(blank=True, null=True)),
                ('prediction_model_top_p', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
