# Generated by Django 5.2.5 on 2025-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0004_chatbotsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='follow_up_context',
            new_name='follow_up_model_context',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='follow_up_max_tokens',
            new_name='follow_up_model_max_tokens',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='follow_up_model',
            new_name='follow_up_model_name',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='ner_llm_content',
            new_name='ner_model_context',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='ner_llm_role',
            new_name='prediction_model_context',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='prediction_max_tokens',
            new_name='prediction_model_max_tokens',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='prediction_message',
            new_name='prediction_model_name',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='summarise_model',
            new_name='summarise_model_name',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='summarise_system_content',
            new_name='summarise_model_system_context',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='summarise_user_content',
            new_name='summarise_model_user_context',
        ),
    ]
