# Generated by Django 5.2.5 on 2025-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0005_rename_follow_up_context_chatbotsettings_follow_up_model_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_recommendation_model_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_recommendation_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_recommendation_model_response_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_recommendation_model_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
