# Generated by Django 5.2.5 on 2025-08-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_project_app', '0006_chatbotsettings_treatment_recommendation_model_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='follow_up_model_json_response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='follow_up_model_response_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='follow_up_model_top_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='ner_model_json_response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='ner_model_max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='ner_model_response_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='ner_model_top_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='prediction_model_json_response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='prediction_model_response_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='summarise_model_json_response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='summarise_model_max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='summarise_model_response_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='summarise_model_top_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_model_top_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='treatment_recommendation_model_json_response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
